childBlocks:
  - aSubfield
conditions: null
description: ''
enabled: true
field: bc07ad34-dedb-4130-9d3d-80fa10e906a2 # Flexible Field
group: null
groupChildBlockTypes: true
handle: aField
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 2
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'A field'
topLevel: true
