columnSuffix: null
contentColumnType: string
fieldGroup: f4d80fe1-e5ac-46ba-8664-323c3c5627a9 # Common
handle: flexibleField
instructions: null
name: 'Flexible Field'
searchable: false
settings:
  maxBlocks: null
  maxLevels: null
  maxTopBlocks: null
  minBlocks: null
  minLevels: null
  minTopBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
